version: "3"

services:
  papercups:
    build: .
    container_name: ${APP_NAME}_papercups
    ports:
      - 3001:3001
      - 4000:4000
    links:
      - postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres:alpine
    container_name: ${APP_NAME}_postgresql
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  db-data: ~
